name: Deploy Development Branch

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "❌ EC2_HOST is not set!"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ EC2_SSH_KEY is not set!"
            exit 1
          fi
          echo "✅ Secrets look fine."

      - name: Deploy and Restart on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/movie-recommendation
            git pull origin development
            npm ci
            npm run build
            pm2 restart movie-recommendation || pm2 start dist/server.js --name movie-recommendation
